### ISSUE TITLE
zig-dev@0.11.0-dev.1247+87b223428: hash check failed

### ISSUE THREAD

**Issue by qtigercom** [enndubyu/scoop-zig#3]

**Comment by enndubyu** [comment]
Both 1247 and the newer build 1253 appear to have the correct hash. If you're still having issues with the new version, you can try doing `scoop cache rm zig-dev` or failing that, downloading the file with a web browser and verifying that there's not a corporate firewall or something interfering with the download.

```
zig-dev: 0.11.0-dev.48+678f3f6e6 -> 0.11.0-dev.1253+fcee1bf99
Updating one outdated app:
Updating 'zig-dev' (0.11.0-dev.48+678f3f6e6 -> 0.11.0-dev.1253+fcee1bf99)
Downloading new version
zig-windows-x86_64-0.11.0-dev.1253+fcee1bf99.zip (70.3 MB) [========================================] 100%
Checking hash of zig-windows-x86_64-0.11.0-dev.1253+fcee1bf99.zip ... ok.
Uninstalling 'zig-dev' (0.11.0-dev.48+678f3f6e6)
Removing shim 'zig.shim.zig-dev'.
Removing shim 'zig-dev.shim'.
Removing shim 'zig-dev.exe'.
Unlinking ~\scoop\apps\zig-dev\current
Installing 'zig-dev' (0.11.0-dev.1253+fcee1bf99) [64bit] from scoop-zig bucket
Loading zig-windows-x86_64-0.11.0-dev.1253+fcee1bf99.zip from cache
Extracting zig-windows-x86_64-0.11.0-dev.1253+fcee1bf99.zip ... done.
Linking ~\scoop\apps\zig-dev\current => ~\scoop\apps\zig-dev\0.11.0-dev.1253+fcee1bf99
Creating shim for 'zig'.
WARN  Overwriting shim ('zig.exe' -> 'zig.exe') installed from zig
Creating shim for 'zig-dev'.
Running post_install script...
Resetting zig (0.10.0).
Linking ~\scoop\apps\zig\current => ~\scoop\apps\zig\0.10.0
Creating shim for 'zig'.
WARN  Overwriting shim ('zig.exe' -> 'zig.exe') installed from zig-dev
'zig-dev' (0.11.0-dev.1253+fcee1bf99) was installed successfully!
```

**Comment by qtigercom** [comment]
for 0.11.0-dev.1253+fcee1bf99, hash in zig-dev.json is ea591b8c36cfbd6443ce3e6f596f2090c0ee79df0a4187be704500bd685e98bd, but for the same file on the original 
 official url, the hash is fca312e40a0c93eba8de31c47eb7bfc3b0c1107d44f7838764df02ba19c5729e 

![20230110103110](https://user-images.githubusercontent.com/1834742/211448551-b229e126-9038-4b74-9dbd-1446f36e581b.png)

**Comment by TheRealDxRed** [comment]
Running into the same problem on my machine, but found a temporary workaround. Assuming you *really* trust the source, you can use the ``-s`` flag to skip the hash check entirely, e.g. ``scoop update -s zig-dev``

**Comment by enndubyu** [comment]
I re-ran the script that scrapes for updates and it found the correct hash. What's weird is that my copy of scoop is still downloading a file with the older hash:

![image](https://user-images.githubusercontent.com/227141/211688661-efe6849f-3b70-41aa-9730-c04d6aff88cf.png)

I'm wondering if there is an old version of this zip file cached in a CDN or something...

You should be able to install now, but I'm going to leave this issue open so that I can take a deeper look when I have more time.

**Comment by enndubyu** [comment]
Last few times I've checked the hash is has matched the one the official website, so I'm going to close this issue even though I don't have a satisfying explanation for the failure.
